/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package supermarket;

import java.awt.TextArea;
import java.awt.print.PrinterException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import static javax.management.Query.value;
import static javax.management.Query.value;
import static javax.management.Query.value;
import static javax.management.Query.value;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author DELL
 */
public class BillingPoint extends javax.swing.JFrame {

    /**
     * Creates new form BillingPoint
     */
    ResultSet Rs, Rs1=null;
    public BillingPoint() throws SQLException {
        initComponents();
        Selected();
        GetCat();
       
        //TextArea.setText();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Name = new javax.swing.JTextField();
        Qty = new javax.swing.JTextField();
        ABill = new javax.swing.JButton();
        Clear = new javax.swing.JButton();
        ComboBox = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        Filter = new javax.swing.JButton();
        Refresh = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Table1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        TextArea = new javax.swing.JTextArea();
        X = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        rs = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 26)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 51, 51));
        jLabel1.setText("Billing Point");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 30, 187, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 255));
        jLabel2.setText("QUANTITY");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(97, 184, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 102, 255));
        jLabel3.setText("NAME");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(97, 137, -1, -1));
        jPanel1.add(Name, new org.netbeans.lib.awtextra.AbsoluteConstraints(234, 132, 131, 30));

        Qty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QtyActionPerformed(evt);
            }
        });
        jPanel1.add(Qty, new org.netbeans.lib.awtextra.AbsoluteConstraints(234, 179, 131, 30));

        ABill.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        ABill.setText("Add to Bill");
        ABill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ABillActionPerformed(evt);
            }
        });
        jPanel1.add(ABill, new org.netbeans.lib.awtextra.AbsoluteConstraints(86, 227, 141, -1));

        Clear.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Clear.setText("Clear");
        Clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearActionPerformed(evt);
            }
        });
        jPanel1.add(Clear, new org.netbeans.lib.awtextra.AbsoluteConstraints(255, 227, -1, -1));

        ComboBox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ComboBoxMouseClicked(evt);
            }
        });
        jPanel1.add(ComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 120, 95, 29));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel4.setText("PRODUCTS LIST");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 80, -1, -1));

        Filter.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        Filter.setText("Filter");
        Filter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FilterActionPerformed(evt);
            }
        });
        jPanel1.add(Filter, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 120, -1, -1));

        Refresh.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        Refresh.setText("Refresh");
        Refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RefreshActionPerformed(evt);
            }
        });
        jPanel1.add(Refresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 120, -1, -1));

        Table1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Name", "Qty", "Price", "Category"
            }
        ));
        Table1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Table1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Table1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 170, 441, 90));

        TextArea.setColumns(20);
        TextArea.setRows(5);
        jScrollPane2.setViewportView(TextArea);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 290, 440, 200));

        X.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        X.setForeground(new java.awt.Color(0, 0, 255));
        X.setText("X");
        X.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                XMouseClicked(evt);
            }
        });
        jPanel1.add(X, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 10, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon("C:\\Users\\DELL\\Desktop\\SuperMarket\\intro-1587139705.jpg")); // NOI18N
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 530));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setText("Print");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        rs.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        rs.setText("Rs");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(rs)
                .addGap(172, 172, 172)
                .addComponent(jButton1)
                .addGap(134, 134, 134))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 527, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(rs))
                .addGap(0, 20, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void QtyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QtyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_QtyActionPerformed

    private void ClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearActionPerformed
        Name.setText("");
        Qty.setText("");
    }//GEN-LAST:event_ClearActionPerformed

    private void XMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_XMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_XMouseClicked
       
    int availqty, Num;
double uprice, ProdTot=0.0, grdtotal=0.0;
    private void Table1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Table1MouseClicked
        // TODO add your handling code here:
        DefaultTableModel model=(DefaultTableModel)Table1.getModel();
        int row=Table1.getSelectedRow();
         Num=Integer.parseInt(model.getValueAt(row, 0).toString());
        availqty=Integer.parseInt(model.getValueAt(row, 3).toString());
        Name.setText(model.getValueAt(row, 1).toString());
         uprice=Double.valueOf(model.getValueAt(row, 4).toString());
        
    }//GEN-LAST:event_Table1MouseClicked

   
    
    public void Selected() throws SQLException{
      Connection Con=DriverManager.getConnection("jdbc:derby://localhost:1527/SuperMarket", "root", "12345");
      String sql="select * from PRODUCTS";
      PreparedStatement ps=Con.prepareStatement(sql);
      Rs=ps.executeQuery();
      Table1.setModel(DbUtils.resultSetToTableModel(Rs));
    }
      public void GetCat() throws SQLException{
     Connection Con=DriverManager.getConnection("jdbc:derby://localhost:1527/SuperMarket", "root", "12345");   
      PreparedStatement ps=Con.prepareStatement("select * from CATEGORIES");
      Rs=ps.executeQuery();
      while(Rs.next()){
          String MyCat=Rs.getString("CName");
          ComboBox.addItem(MyCat);
      }
    }
    
     public void update(){
          try {
                Connection Con=DriverManager.getConnection("jdbc:derby://localhost:1527/SuperMarket", "root", "12345");
                //String sql="update products SET  qty=? where name="+Name.getText();
                
                PreparedStatement ps=Con.prepareStatement("Update products SET QTY=? where PID="+Num);
                ps.setInt(1, rem);
                ps.executeUpdate();
                Selected();
                Con.close();
            
            } catch (SQLException ex) {
               ex.printStackTrace();
            }
    }
     
      int i=0, rem=0;
    private void ABillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ABillActionPerformed
        if(Name.getText().isEmpty() || Qty.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Missing Requriments");
        }
        else if(availqty<=Integer.valueOf(Qty.getText()))
        {
            JOptionPane.showMessageDialog(this, "Not enough in stock");
        }
        else{
            i++;
            ProdTot=uprice*Integer.valueOf(Qty.getText());
            grdtotal=grdtotal+ProdTot;
            rem=availqty-Integer.valueOf(Qty.getText());
         if(i==1)
         {
        
           TextArea.setText("**********************************FAMILY POINT**********************************\n"+
                   " NUM             PRODNAME                QTY               PRICE              TOTAL\n"+
                   i+"                        "+Name.getText()+"                       "+Qty.getText()+"                      "+uprice+"                  "+ProdTot+"\n");
           
        } 
         else{
             TextArea.setText(TextArea.getText()+i+"                       "+Name.getText()+"                    "+Qty.getText()+"                      "+uprice+"                 "+ProdTot+"\n");
             }
           
         rs.setText("RS:"+grdtotal);
        
    }//GEN-LAST:event_ABillActionPerformed
    }

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
           // TODO add your handling code here:
           update();
            TextArea.setText(TextArea.getText()+"\n\n\n"+"                                                   "+"Total Amount:"+grdtotal);
            TextArea.print();
        } catch (PrinterException ex) {
            Logger.getLogger(BillingPoint.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void ComboBoxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ComboBoxMouseClicked
        // TODO add your handling code here:
      
    }//GEN-LAST:event_ComboBoxMouseClicked

    private void FilterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FilterActionPerformed
        // TODO add your handling code here:
          try{
        Connection Con=DriverManager.getConnection("jdbc:derby://localhost:1527/SuperMarket", "root", "12345");
      String sql="select * from  root.CATEGORIES where CNAME="+ComboBox.getSelectedItem().toString();
      PreparedStatement ps=Con.prepareStatement(sql);
      Rs=ps.executeQuery();
      Table1.setModel(DbUtils.resultSetToTableModel(Rs));
        }
        catch(Exception e){
        e.printStackTrace();
    }
    }//GEN-LAST:event_FilterActionPerformed

    private void RefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RefreshActionPerformed
        try {
            // TODO add your handling code here:
            Selected();
        } catch (SQLException ex) {
            Logger.getLogger(BillingPoint.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_RefreshActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BillingPoint.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BillingPoint.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BillingPoint.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BillingPoint.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new BillingPoint().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(BillingPoint.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ABill;
    private javax.swing.JButton Clear;
    private javax.swing.JComboBox<String> ComboBox;
    private javax.swing.JButton Filter;
    private javax.swing.JTextField Name;
    private javax.swing.JTextField Qty;
    private javax.swing.JButton Refresh;
    private javax.swing.JTable Table1;
    private javax.swing.JTextArea TextArea;
    private javax.swing.JLabel X;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel rs;
    // End of variables declaration//GEN-END:variables
}
