/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package supermarket;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;
import static net.proteanit.sql.DbUtils.resultSetToTableModel;

/**
 *
 * @author DELL
 */
public class ManageCategories extends javax.swing.JFrame {

    /**
     * Creates new form ManageCategories
     */
    
    public ManageCategories() throws SQLException {
        initComponents();
        Selected();
    }
ResultSet Rs=null;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        CatId = new javax.swing.JTextField();
        Desc = new javax.swing.JTextField();
        Name = new javax.swing.JTextField();
        Add = new javax.swing.JButton();
        Delete = new javax.swing.JButton();
        Update = new javax.swing.JButton();
        Clear = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Table1 = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        Products = new javax.swing.JLabel();
        Sellers = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);

        jPanel1.setBackground(new java.awt.Color(255, 153, 0));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 28)); // NOI18N
        jLabel1.setText("MANAGE CATEGORIES");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(289, 13, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("CATID");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(242, 102, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("NAME");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(247, 156, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("DESCRIPTION");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 196, -1, -1));
        jPanel1.add(CatId, new org.netbeans.lib.awtextra.AbsoluteConstraints(334, 104, 117, 29));
        jPanel1.add(Desc, new org.netbeans.lib.awtextra.AbsoluteConstraints(334, 189, 117, 29));
        jPanel1.add(Name, new org.netbeans.lib.awtextra.AbsoluteConstraints(334, 147, 117, 31));

        Add.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Add.setText("Add");
        Add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddActionPerformed(evt);
            }
        });
        jPanel1.add(Add, new org.netbeans.lib.awtextra.AbsoluteConstraints(527, 98, 97, -1));

        Delete.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Delete.setText("Delete");
        Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteActionPerformed(evt);
            }
        });
        jPanel1.add(Delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 98, -1, -1));

        Update.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Update.setText("Update");
        Update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateActionPerformed(evt);
            }
        });
        jPanel1.add(Update, new org.netbeans.lib.awtextra.AbsoluteConstraints(527, 164, -1, -1));

        Clear.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Clear.setText("Clear");
        Clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearActionPerformed(evt);
            }
        });
        jPanel1.add(Clear, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 164, 91, -1));

        Table1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CATID", "NAME", "DESCRIPTION"
            }
        ));
        Table1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Table1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Table1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 269, 591, 176));

        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\DELL\\Desktop\\SuperMarket\\__opt__aboutcom__coeus__resources__content_migration__treehugger__images__2020__04__grocery-cart-a12224a52f8f4e42a3a5464cfe0caa28.jpg")); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 0, 690, 460));

        Products.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Products.setForeground(new java.awt.Color(0, 0, 255));
        Products.setText("Products");
        Products.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ProductsMouseClicked(evt);
            }
        });
        jPanel1.add(Products, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        Sellers.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Sellers.setForeground(new java.awt.Color(0, 0, 255));
        Sellers.setText("Sellers");
        Sellers.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SellersMouseClicked(evt);
            }
        });
        jPanel1.add(Sellers, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setText("LogOut");
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 430, -1, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearActionPerformed
       CatId.setText("");
       Name.setText("");
       Desc.setText("");
    }//GEN-LAST:event_ClearActionPerformed

    public void Selected() throws SQLException{
         Connection Con=DriverManager.getConnection("jdbc:derby://localhost:1527/SuperMarket", "root", "12345");
         String query="select * from categories";
         PreparedStatement ps= Con.prepareStatement(query);
         Rs= ps.executeQuery();
         Table1.setModel(DbUtils.resultSetToTableModel(Rs));
    }
    private void AddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddActionPerformed
        if(CatId.getText().isEmpty()|| Name.getText().isEmpty()||Desc.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Missing Requirrements");
        }else{
        try {
            Connection Con=DriverManager.getConnection("jdbc:derby://localhost:1527/SuperMarket", "root", "12345");
            PreparedStatement ps=Con.prepareStatement("insert into categories Values(?,?,?)");
            ps.setInt(1, Integer.parseInt(CatId.getText()));
            ps.setString(2, Name.getText());
            ps.setString(3, Desc.getText());
            ps.executeUpdate();
            JOptionPane.showMessageDialog(this, "Added sucessfully");
            Selected();
            Con.close();
        } catch (SQLException ex) {
           ex.printStackTrace();
        }
    }//GEN-LAST:event_AddActionPerformed
    }
        
        
    private void DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteActionPerformed
        if(CatId.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Please Enter catId");
        }else{
        try {
            // TODO add your handling code here:
            Connection Con=DriverManager.getConnection("jdbc:derby://localhost:1527/SuperMarket", "root", "12345");
            String id=CatId.getText();
            PreparedStatement ps=Con.prepareStatement("delete from categories where cid="+ id);
            ps.executeUpdate();
            JOptionPane.showMessageDialog(this, "Deleted sucessfully");
            Con.close();
            Selected();
        } catch (SQLException ex) {
        ex.printStackTrace();
        }
    }//GEN-LAST:event_DeleteActionPerformed
    }
    private void Table1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Table1MouseClicked
        // TODO add your handling code here:
        DefaultTableModel model=(DefaultTableModel)Table1.getModel();
        int row=Table1.getSelectedRow();
        CatId.setText(model.getValueAt(row, 0).toString());
        Name.setText(model.getValueAt(row, 1).toString());
        Desc.setText(model.getValueAt(row, 2).toString());
    }//GEN-LAST:event_Table1MouseClicked

    private void UpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateActionPerformed
        if(CatId.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Please Select the Item to Update");
        }else{
        try {
            // TODO add your handling code here:
            Connection Con=DriverManager.getConnection("jdbc:derby://localhost:1527/SuperMarket", "root", "12345");
            String value=CatId.getText();
            PreparedStatement ps=Con.prepareStatement("Update categories SET cid=?, cname=?, Description=? where cid="+value);
            ps.setInt(1, Integer.valueOf(CatId.getText()));
            ps.setString(2, Name.getText());
            ps.setString(3, Desc.getText());
            ps.executeUpdate();
            JOptionPane.showMessageDialog(this, "Update has been sucessfully");
            Selected();
            Con.close();
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_UpdateActionPerformed
    }
    
    private void ProductsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ProductsMouseClicked
        try {
            // TODO add your handling code here:
            new ManageProducts().setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(ManageCategories.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.dispose();
    }//GEN-LAST:event_ProductsMouseClicked

    private void SellersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SellersMouseClicked
        try {
            // TODO add your handling code here:
            new ManageSellers().setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(ManageCategories.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.dispose();
    }//GEN-LAST:event_SellersMouseClicked

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        // TODO add your handling code here:
        new LogIn1().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel9MouseClicked
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManageCategories.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManageCategories.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManageCategories.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManageCategories.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new ManageCategories().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(ManageCategories.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Add;
    private javax.swing.JTextField CatId;
    private javax.swing.JButton Clear;
    private javax.swing.JButton Delete;
    private javax.swing.JTextField Desc;
    private javax.swing.JTextField Name;
    private javax.swing.JLabel Products;
    private javax.swing.JLabel Sellers;
    private javax.swing.JTable Table1;
    private javax.swing.JButton Update;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
