/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package supermarket;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author DELL
 */
public class ManageProducts extends javax.swing.JFrame {

    /**
     * Creates new form ManageProducts
     */
    Connection Con=null;
    ResultSet Rs=null;
    public ManageProducts() throws SQLException {
        initComponents();
        Selected();
        GetCat();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        ProdId = new javax.swing.JTextField();
        Name = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Qty = new javax.swing.JTextField();
        Price = new javax.swing.JTextField();
        Category = new javax.swing.JComboBox<>();
        Add = new javax.swing.JButton();
        Update = new javax.swing.JButton();
        Delete = new javax.swing.JButton();
        Clear = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Table1 = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        Cat = new javax.swing.JLabel();
        Seller = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 153, 0));
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 153, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 26)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 255, 51));
        jLabel1.setText("MANAGE PRODUCTS");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 20, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 255, 51));
        jLabel2.setText("NAME");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(188, 117, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 255, 51));
        jLabel3.setText("PRODID");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(165, 82, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 255, 51));
        jLabel4.setText("CATEGORY");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(143, 152, -1, -1));
        jPanel1.add(ProdId, new org.netbeans.lib.awtextra.AbsoluteConstraints(282, 76, 106, 30));
        jPanel1.add(Name, new org.netbeans.lib.awtextra.AbsoluteConstraints(282, 111, 106, 30));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 255, 51));
        jLabel5.setText("QUANTITY");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(473, 82, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 255, 51));
        jLabel6.setText("PRICE");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(473, 117, -1, -1));
        jPanel1.add(Qty, new org.netbeans.lib.awtextra.AbsoluteConstraints(601, 76, 104, 30));
        jPanel1.add(Price, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 110, 104, 30));

        Category.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel1.add(Category, new org.netbeans.lib.awtextra.AbsoluteConstraints(282, 146, 106, 30));

        Add.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Add.setText("Add");
        Add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddActionPerformed(evt);
            }
        });
        jPanel1.add(Add, new org.netbeans.lib.awtextra.AbsoluteConstraints(174, 223, -1, -1));

        Update.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Update.setText("Update");
        Update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateActionPerformed(evt);
            }
        });
        jPanel1.add(Update, new org.netbeans.lib.awtextra.AbsoluteConstraints(296, 223, -1, -1));

        Delete.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Delete.setText("Delete");
        Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteActionPerformed(evt);
            }
        });
        jPanel1.add(Delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(448, 223, -1, -1));

        Clear.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Clear.setText("Clear");
        Clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearActionPerformed(evt);
            }
        });
        jPanel1.add(Clear, new org.netbeans.lib.awtextra.AbsoluteConstraints(601, 223, -1, -1));

        Table1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "PRODID", "NAME", "CATEGORY", "QUANTITY", "PRICE"
            }
        ));
        Table1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Table1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Table1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 300, 700, 172));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("X");
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 10, 20, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon("C:\\Users\\DELL\\Desktop\\SuperMarket\\2.jpg")); // NOI18N
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, -50, 740, 550));

        Cat.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Cat.setText("CATEGORIES");
        Cat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CatMouseClicked(evt);
            }
        });
        jPanel1.add(Cat, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, -1, -1));

        Seller.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Seller.setText("SELLER");
        Seller.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SellerMouseClicked(evt);
            }
        });
        jPanel1.add(Seller, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    public void Selected() throws SQLException{
        Con=DriverManager.getConnection("jdbc:derby://localhost:1527/SuperMarket", "root", "12345");
        
         PreparedStatement ps=Con.prepareStatement("select * from PRODUCTS");
         Rs=ps.executeQuery();
        Table1.setModel(DbUtils.resultSetToTableModel(Rs));
               
         }
    public void GetCat() throws SQLException{
      Con=DriverManager.getConnection("jdbc:derby://localhost:1527/SuperMarket", "root", "12345");   
      PreparedStatement ps=Con.prepareStatement("select * from CATEGORIES");
      Rs=ps.executeQuery();
      while(Rs.next()){
          String MyCat=Rs.getString("CName");
          Category.addItem(MyCat);
      }
    }
    
    private void ClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearActionPerformed
     ProdId.setText("");
     Name.setText("");
     Category.setSelectedItem("");
     Qty.setText("");
     Price.setText("");
    }//GEN-LAST:event_ClearActionPerformed

    private void AddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddActionPerformed
       try {
            Con=DriverManager.getConnection("jdbc:derby://localhost:1527/SuperMarket", "root", "12345");
            PreparedStatement ps=Con.prepareStatement("insert into PRODUCTS Values (?,?,?,?,?)");
            ps.setInt(1, Integer.valueOf(ProdId.getText()));
             ps.setString(2, Name.getText());
              ps.setString(3, Category.getSelectedItem().toString());
             ps.setInt(4, Integer.valueOf(Qty.getText()));
              ps.setInt(5, Integer.valueOf(Price.getText()));
             ps.executeUpdate();
            JOptionPane.showMessageDialog(this, "Data Added Sucessfully");
            
            Selected();
            Con.close();
        } catch (SQLException ex) {
           ex.printStackTrace();
        }
    }//GEN-LAST:event_AddActionPerformed

    private void SellerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SellerMouseClicked
        try {
            // TODO add your handling code here:
            new ManageSellers().setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(ManageProducts.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.dispose();
    }//GEN-LAST:event_SellerMouseClicked

    private void CatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CatMouseClicked
        try {
            // TODO add your handling code here:
            new ManageCategories().setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(ManageProducts.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.dispose();
    }//GEN-LAST:event_CatMouseClicked

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jLabel7MouseClicked

    private void DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteActionPerformed
        try {
            // TODO add your handling code here:
            Con=DriverManager.getConnection("jdbc:derby://localhost:1527/SuperMarket", "root", "12345");
            String id=ProdId.getText();
              PreparedStatement ps=Con.prepareStatement("delete from Products where pid="+ id);
              ps.executeUpdate();
              JOptionPane.showMessageDialog(this, "Deleted Sucessfully");
              Selected();
              Con.close();
        } catch (SQLException ex) {
           ex.printStackTrace();
        }
          
   
    }//GEN-LAST:event_DeleteActionPerformed

    private void Table1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Table1MouseClicked
        // TODO add your handling code here:
        DefaultTableModel model=(DefaultTableModel)Table1.getModel();
        int row=Table1.getSelectedRow();
        ProdId.setText(model.getValueAt(row, 0).toString());
        Name.setText(model.getValueAt(row, 1).toString());
       Category.setSelectedItem(model.getValueAt(row, 2).toString());
       Qty.setText(model.getValueAt(row, 3).toString());
       Price.setText(model.getValueAt(row, 4).toString());
    }//GEN-LAST:event_Table1MouseClicked

    private void UpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateActionPerformed
        if(ProdId.getText().isEmpty()|| Name.getText().isEmpty()||Qty.getText().isEmpty()||Price.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "missing Requirements");
        }else{
        try {
            // TODO add your handling code here:
            Con=DriverManager.getConnection("jdbc:derby://localhost:1527/SuperMarket", "root", "12345");
            String value=ProdId.getText();
  PreparedStatement ps=Con.prepareStatement("update PRODUCTS set pid=?, name=?, category=?, qty=?, price=? where pid="+value);
        ps.setInt(1, Integer.valueOf(ProdId.getText()));
        ps.setString(2, Name.getText());
        ps.setString(3, Category.getSelectedItem().toString());
        ps.setInt(4, Integer.valueOf(Qty.getText()));
        ps.setInt(5, Integer.valueOf(Price.getText()));
        ps.executeUpdate();
        Selected();
        JOptionPane.showMessageDialog(this, "Deleted Sucessfully");
        Con.close();
                
        } catch (SQLException ex) {
           ex.printStackTrace();
        }
    }//GEN-LAST:event_UpdateActionPerformed
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManageProducts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManageProducts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManageProducts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManageProducts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new ManageProducts().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(ManageProducts.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Add;
    private javax.swing.JLabel Cat;
    private javax.swing.JComboBox<String> Category;
    private javax.swing.JButton Clear;
    private javax.swing.JButton Delete;
    private javax.swing.JTextField Name;
    private javax.swing.JTextField Price;
    private javax.swing.JTextField ProdId;
    private javax.swing.JTextField Qty;
    private javax.swing.JLabel Seller;
    private javax.swing.JTable Table1;
    private javax.swing.JButton Update;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
